const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Button,
		C3.Plugins.GamePush_Channels,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.HTMLElement,
		C3.Plugins.Touch,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Button.Acts.SetText,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Button.Cnds.PickByUID,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerAdd,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Eponesh_GameScore.Cnds.VariablesCompare,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerID
	];
};
self.C3_JsPropNameTable = [
	{Платформер: 0},
	{G_Bomb_Game1: 0},
	{G_Coin_Game1: 0},
	{Spawner_Dead: 0},
	{Якорь: 0},
	{GCoins_Game1_txt: 0},
	{TimerButton: 0},
	{Bomb_Effect: 0},
	{GamePushChannels: 0},
	{GamePush: 0},
	{Loading_html: 0},
	{Text: 0},
	{Тач: 0},
	{Твинанимация: 0},
	{MenuButton: 0},
	{BackgroundButton: 0},
	{Username: 0},
	{UserID: 0},
	{ТайловыйФон: 0},
	{Game1_Start: 0},
	{Timer_Game1: 0},
	{Menu_Steek: 0},
	{G_Coins: 0}
];

self.InstanceType = {
	G_Bomb_Game1: class extends self.ISpriteInstance {},
	G_Coin_Game1: class extends self.ISpriteInstance {},
	Spawner_Dead: class extends self.ISpriteInstance {},
	GCoins_Game1_txt: class extends self.ITextInstance {},
	TimerButton: class extends self.IButtonInstance {},
	Bomb_Effect: class extends self.ISpriteInstance {},
	GamePushChannels: class extends self.C3.Plugins.GamePush_Channels.Instance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	Loading_html: class extends self.IHTMLElementInstance {},
	Text: class extends self.ITextInstance {},
	Тач: class extends self.IInstance {},
	MenuButton: class extends self.IButtonInstance {},
	BackgroundButton: class extends self.IButtonInstance {},
	Username: class extends self.ITextInstance {},
	UserID: class extends self.ITextInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {}
}